# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3b85dc2d870ab6a1635787ae2dcd982a9cdba4f448c70205331c92e59197e068b653f0df769b890b580121a4e4e54d6ca3a196cb265b67ae33adca78370fd93

test:
  secret_key_base: 73f2f4c78d1760dce75df313d2a5a1a3413636615f37fcdd44108b9e7e29ec14441dfcb47e374131658780ab97d64044da6f7cb6dfd9ab7b3bf139ca031dee20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
